# Generated by Django 5.0.1 on 2024-11-17 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deck_cover_card_alter_deck_color_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckReaction',
            fields=[
                ('react_id', models.AutoField(primary_key=True, serialize=False)),
                ('emoji', models.CharField(choices=[('⚡', 'Lightning'), ('🔥', 'Fire'), ('🌿', 'Leaf'), ('💧', 'Water'), ('⭐', 'Star'), ('✨', 'Sparkles'), ('💪', 'Strong'), ('🎯', 'Target'), ('❤️', 'Heart'), ('👍', 'Thumbs Up'), ('👎', 'Thumbs Down'), ('🏆', 'Trophy')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('deck', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='DeckVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('deck', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
