# Generated by Django 5.0.1 on 2024-11-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cover_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_decks', to='core.card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='color_1',
            field=models.CharField(choices=[('grass', 'Grass'), ('fire', 'Fire'), ('water', 'Water'), ('lightning', 'Lightning'), ('fighting', 'Fighting'), ('psychic', 'Psychic'), ('colorless', 'Colorless'), ('darkness', 'Darkness'), ('metal', 'Metal'), ('dragon', 'Dragon'), ('fairy', 'Fairy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='deck',
            name='color_2',
            field=models.CharField(choices=[('grass', 'Grass'), ('fire', 'Fire'), ('water', 'Water'), ('lightning', 'Lightning'), ('fighting', 'Fighting'), ('psychic', 'Psychic'), ('colorless', 'Colorless'), ('darkness', 'Darkness'), ('metal', 'Metal'), ('dragon', 'Dragon'), ('fairy', 'Fairy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='deck',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deck',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
